apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopnow-ingress
spec:
  rules:
    - host: shopnow.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shopnow-frontend
                port:
                  number: 80
