backend:
  replicas: 2
  image:
    repository: rajeshpawar012/shopnow-backend
    tag: latest
  containerPort: 5000
  service:
    port: 5000
    targetPort: 5000

frontend:
  replicas: 2
  image:
    repository: rajeshpawar012/shopnow-frontend
    tag: latest

  service:
    type: NodePort
    port: 80
    nodePort: 30080


